export { default as SpaceMono } from './SpaceMono-Regular.ttf'
export { default as Roboto } from './Roboto-Regular.ttf'
export { default as RobotoBold } from './Roboto-Bold.ttf'
export { default as RobotoMedium } from './Roboto-Medium.ttf'
export { default as RobotoLight } from './Roboto-Light.ttf'
export { default as RobotoThin } from './Roboto-Thin.ttf'
export { default as RobotoBlack } from './Roboto-Black.ttf'
